id: AD30A70A6
title: Prayer to My Root Guru, Jamyang Loter Wangpo
type: translation
pechas:
- I3EBD9916
- IBEBD3395
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:38:30.690054
  last_modified_at: 2023-01-04 12:38:30.690056
  collections:
  - Jamyang Loter Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I3EBD9916/8622: BDA7
  IBEBD3395/A8D4: BDA7
